env: "local" # local, dev, test, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # Время на чтение запроса, плюс такое же время на запись
  idle_timeout: 60s # Время жизни соединения с клиентом